### ISSUE TITLE
NO utils!~

### ISSUE THREAD

**Issue by irfanICMLL** [csbkwang/ACMR_demo#1]
Hi,
    Thanks for your contribution on the ACMR model! It is really an excellent work~ I want to try the code, but I find the code is not complete~ UTILS are needed for the experiment~
   What's more, I find that adv += domain_loss_val. And I have some difficulities to understand this. It is a little different from the equations in the paper~
   Would u mind that I contact you by wechat? It will be more convenient~

**Comment by FredHuang16** [comment]
Same problem

**Comment by csbkwang** [comment]
I have uploaded the "utils.py". Thanks.
